# Generated by Django 3.0.7 on 2020-07-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('LanguageName', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingTutorial',
            fields=[
                ('postId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ptAuthor', models.CharField(max_length=200)),
                ('ptTitle', models.CharField(max_length=200)),
                ('ptTimeDate', models.DateTimeField(auto_now_add=True)),
                ('ptInC', models.TextField()),
                ('ptInCplus', models.TextField()),
                ('ptInPython', models.TextField()),
                ('ptDescriptions', models.TextField()),
                ('ptUrl', models.TextField(blank=True)),
                ('ptImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('views', models.IntegerField(default=0)),
                ('languageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmingTutorial.Language')),
            ],
        ),
    ]
