# Generated by Django 3.0.7 on 2020-07-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingTutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingtutorial',
            old_name='ptInC',
            new_name='ptCode',
        ),
        migrations.RemoveField(
            model_name='programmingtutorial',
            name='ptInCplus',
        ),
        migrations.RemoveField(
            model_name='programmingtutorial',
            name='ptInPython',
        ),
    ]
