# Generated by Django 2.2.13 on 2021-03-14 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postBody',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
