# Generated by Django 2.2.13 on 2021-03-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_postbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postInC',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postInCplus',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postInPython',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postUrl',
        ),
    ]
